import fs from "fs/promises";
import path from "path";
import os from "os";

import config from "../config.js";

import {
  registerProject,
  setProjectStatus
} from "../services/projectManager.js";

import {
  processProjectZip
} from "../services/zipManager.js";

import {
  createOrUpdateUser
} from "../database.js";

// ─────────────────────────────────────────────
// UPLOAD HANDLER
// ─────────────────────────────────────────────

export function registerUploadHandler(bot) {
  bot.on("document", async (msg) => {
    const chatId = msg.chat.id;
    const document = msg.document;

    if (!document) return;

    const fileName =
      document.file_name || "upload.zip";

    // Only ZIP projects for now.
    if (
      path.extname(fileName).toLowerCase() !== ".zip"
    ) {
      await bot.sendMessage(
        chatId,
        "❌ <b>Invalid file</b>\n\nPlease send your website as a <code>.zip</code> file.",
        {
          parse_mode: "HTML"
        }
      );

      return;
    }

    const maxBytes =
      config.maxFileSizeMB * 1024 * 1024;

    if (
      document.file_size &&
      document.file_size > maxBytes
    ) {
      await bot.sendMessage(
        chatId,
        `❌ <b>File too large</b>\n\nMaximum allowed size: <b>${config.maxFileSizeMB} MB</b>.`,
        {
          parse_mode: "HTML"
        }
      );

      return;
    }

    let project = null;
    let temporaryFile = null;

    try {
      // Make sure the user exists.
      await createOrUpdateUser(msg.from);

      await bot.sendMessage(
        chatId,
        "⏳ <b>Upload received</b>\n\nPreparing your project...",
        {
          parse_mode: "HTML"
        }
      );

      // ───────────────────────────────────────
      // DOWNLOAD TELEGRAM FILE
      // ───────────────────────────────────────

      const telegramFile =
        await bot.getFile(document.file_id);

      const fileUrl =
        `https://api.telegram.org/file/bot${config.botToken}/${telegramFile.file_path}`;

      const response =
        await fetch(fileUrl);

      if (!response.ok) {
        throw new Error(
          "Unable to download the Telegram file."
        );
      }

      const buffer =
        Buffer.from(
          await response.arrayBuffer()
        );

      if (buffer.length > maxBytes) {
        throw new Error(
          `Downloaded file exceeds the ${config.maxFileSizeMB} MB limit.`
        );
      }

      temporaryFile = path.join(
        os.tmpdir(),
        `telegram-hosting-${Date.now()}-${msg.from.id}.zip`
      );

      await fs.writeFile(
        temporaryFile,
        buffer
      );

      // ───────────────────────────────────────
      // CREATE PROJECT
      // ───────────────────────────────────────

      const baseName =
        path.basename(
          fileName,
          path.extname(fileName)
        );

      project = await registerProject({
        userId: msg.from.id,
        name: baseName,
        size: buffer.length,
        files: 0
      });

      await setProjectStatus(
        project.id,
        "deploying",
        msg.from.id
      );

      await bot.sendMessage(
        chatId,
        `
🔍 <b>Validating project...</b>

📦 File: <code>${escapeHtml(fileName)}</code>
💾 Size: <b>${formatBytes(buffer.length)}</b>

Please wait...
`,
        {
          parse_mode: "HTML"
        }
      );

      // ───────────────────────────────────────
      // PROCESS ZIP
      // ───────────────────────────────────────

      const result =
        await processProjectZip(
          temporaryFile,
          project.id
        );

      await setProjectStatus(
        project.id,
        "active",
        msg.from.id
      );

      await bot.sendMessage(
        chatId,
        `
✅ <b>Project prepared successfully!</b>

━━━━━━━━━━━━━━━━━━

📁 Project:
<b>${escapeHtml(project.name)}</b>

🆔 ID:
<code>${project.id}</code>

📦 Files:
<b>${result.files}</b>

💾 Size:
<b>${formatBytes(result.size)}</b>

🟢 Status:
<b>READY</b>

━━━━━━━━━━━━━━━━━━

🌐 <i>Deployment URL will be generated by the hosting engine.</i>
`,
        {
          parse_mode: "HTML",
          reply_markup: {
            inline_keyboard: [
              [
                {
                  text: "📁 My Projects",
                  callback_data: "my_projects"
                }
              ],
              [
                {
                  text: "🏠 Main Menu",
                  callback_data: "main_menu"
                }
              ]
            ]
          }
        }
      );
    } catch (error) {
      console.error(
        "❌ Upload processing error:",
        error
      );

      if (project) {
        try {
          await setProjectStatus(
            project.id,
            "failed",
            msg.from.id
          );
        } catch {
          // Ignore secondary database error.
        }
      }

      let message =
        "❌ <b>Project processing failed.</b>";

      if (
        error.message?.includes(
          "index.html"
        )
      ) {
        message +=
          "\n\n📄 Your ZIP must contain an <code>index.html</code> file in the website root.";
      } else if (
        error.message?.includes(
          "exceeds"
        )
      ) {
        message +=
          `\n\n💾 Maximum project size is <b>${config.maxFileSizeMB} MB</b>.`;
      } else if (
        error.message?.includes(
          "Unsupported file"
        )
      ) {
        message +=
          "\n\n📁 Your project contains an unsupported file type.";
      } else {
        message +=
          "\n\nPlease check your ZIP and try again.";
      }

      await bot.sendMessage(
        chatId,
        message,
        {
          parse_mode: "HTML"
        }
      );
    } finally {
      // Always remove temporary Telegram download.
      if (temporaryFile) {
        try {
          await fs.rm(
            temporaryFile,
            {
              force: true
            }
          );
        } catch {
          // Ignore cleanup errors.
        }
      }
    }
  });
}

// ─────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────

function formatBytes(bytes) {
  const value = Number(bytes || 0);

  if (value === 0) {
    return "0 B";
  }

  const units = [
    "B",
    "KB",
    "MB",
    "GB"
  ];

  const index = Math.min(
    Math.floor(
      Math.log(value) / Math.log(1024)
    ),
    units.length - 1
  );

  return `${(
    value /
    Math.pow(1024, index)
  ).toFixed(index === 0 ? 0 : 2)} ${units[index]}`;
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
